name: Push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TIMESTAMP: $(date +%s)
  IMAGE_NAME: ghcr.io/crisszkutnik/dollar-data-to-google-spreadsheets-etl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ${{ IMAGE_NAME }}:${{ TIMESTAMP }}
    - name: Create tag
      run: docker image tag ${{ IMAGE_NAME }}:${{ TIMESTAMP }} ${{ IMAGE_NAME }}:latest
    - name: Push image
      run: docker image push --all-tags ${{ IMAGE_NAME }}:${{ TIMESTAMP }}
