name: Push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64,linux/amd64
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    - name: Delete untagged
      uses: actions/delete-package-versions@v5
      with:
        package-name: ${{ env.REPOSITORY_NAME }}
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: true
