name: Push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/crisszkutnik/dollar-data-to-google-spreadsheets-etl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . -t ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}
    - name: Create tag
      run: docker image tag ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }} ${{ env.IMAGE_NAME }}:latest
    - name: Push image
      run: docker image push --all-tags ${{ env.IMAGE_NAME }}:latest
