name: Push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      Timestamp: $(date +%s)
      Image_Name: ghcr.io/crisszkutnik/dollar-data-to-google-spreadsheets-etl
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ${{ Image_Name }}:${{ Timestamp }}
    - name: Create tag
      run: docker image tag ${{ Image_Name }}:${{ Timestamp }} ${{ Image_Name }}:latest
    - name: Push image
      run: docker image push --all-tags ${{ Image_Name }}:${{ Timestamp }}
